### ISSUE TITLE
Add link to settings from plugins page

### ISSUE THREAD

**Issue by bhubbard** [leftlane/wp101plugin#36]
It would be useful to add a link to the settings page from the plugins page. Yoast SEO has a great example of this:

![](https://www.evernote.com/shard/s1/sh/ef34e163-66c0-40b2-97ba-b2829f046a54/8559486772d68d4e/res/61d2c0af-54c0-40ee-b393-9c603e093343/skitch.png?resizeSmall&width=832)

**Comment by stevegrunwell** [comment]
This feature is included in version 5.0.0 of the plugin 😄
