### ISSUE TITLE
PHP 8.1 - deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string

### ISSUE THREAD

**Issue by claytoncollie** [leftlane/wp101plugin#88]
Hello. I am upgrading my sites to use PHP 8.1 and possibly 8.2. When I change this version and have WP_DEBUG enabled, I see these error messages. When I deactivate this plugin, WP101, the errors go away.

<img width="1260" alt="image" src="https://github.com/awesomemotive/wp101plugin/assets/4236538/a2e93acc-13e4-460f-bc05-2a2685a5fb4e">

<img width="1259" alt="image" src="https://github.com/awesomemotive/wp101plugin/assets/4236538/05e29dd2-bcc7-4818-abb0-382d25de4bb1">

**Comment by awps** [comment]
Hi. This has been fixed in the latest version `5.4.1`.
