### ISSUE TITLE
Invalid offset in request warning

### ISSUE THREAD

**Issue by NicktheGeek** [leftlane/wp101plugin#90]
I help maintain a large network of sites and the logs are being cluttered with the error:
```
PHP message: Warning: Trying to access array offset on value of type null in /var/www/wp-content/plugins/wp101/includes/class-api.php on line 483 

PHP message: Warning: Trying to access array offset on value of type null in /var/www/wp-content/plugins/wp101/includes/class-api.php on line 497
```

There are no checks in the code to ensure the response is valid, so it triggers this error. It is fixed in https://github.com/awesomemotive/wp101plugin/pull/89

**Comment by awps** [comment]
Thank you. Merged
